config/routes.rb
Rails.application.routes.draw do
  resource :sessions
  resource :unsealers
  get "/auth/:provider/callback" => "sessions#create"
  root "unsealers#index"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    User.new(session[:user_email], session[:user_name], session[:user_image]) if session[:user_email]
  end
  helper_method :current_user

end

class User < Struct.new(:email, :name, :image)
end

app/controllers/sessions_controller.rb
require "pp"
class SessionsController < ApplicationController
  def create
    if %w{heroku google}.include? ENV["AUTH"]
      unless email.match(/@#{ENV["AUTHORIZED_DOMAIN"]}$/i)
        flash[:error] = "#{ENV["AUTH"].capitalize}: Unauthorized domain for #{email}"
        redirect_to root_path
        return
      end
    end
    if ENV["AUTH"] == "github"
      client = Octokit::Client.new(access_token: auth[:credentials][:token])
      orgs = client.organizations
      unless orgs.map(&:login).include? ENV["AUTHORIZED_ORG"]
        flash[:error] = "GitHub: Unauthorized organization for #{auth[:info][:nickname]}"
        redirect_to root_path
        return
      end
    end
    session[:user_email] = auth[:info][:email]
    session[:user_name] = auth[:info][:name]
    session[:user_image] = auth[:info][:image]
    redirect_to root_path
  end

  def destroy
    session[:user_email] = nil
    session[:user_name] = nil
    session[:user_image] = nil
    flash[:notice] = "Disconnected"
    redirect_to root_path
  end

  def email
    auth[:info][:email]
  end

  def auth
    pp env["omniauth.auth"]
  end
end

app/controllers/unsealers_controller.rb
class UnsealersController < ApplicationController
  def index
    @status = Vault.sys.seal_status
    render :index
  end

  USER_AGENT = "VaultRuby/0.0.1 (+github.com/hashicorp/vault-ruby)".freeze

  # The default headers that are sent with every request.
  DEFAULT_HEADERS = {
    "Content-Type" => "application/json",
    "Accept"       => "application/json",
    "User-Agent"   => USER_AGENT,
  }

  def create
    shard = ENV["VAULT_SHARD"]
    Excon.put("#{ENV["VAULT_ADDR"]}/v1/sys/unseal", body: {key: shard}.to_json, headers: DEFAULT_HEADERS)
  rescue StandardError => e
    flash[:error] = e.message
  ensure
    redirect_to root_path
  end

  def destroy
    Excon.put("#{ENV["VAULT_ADDR"]}/v1/sys/seal", headers: DEFAULT_HEADERS)
  rescue StandardError => e
    flash[:error] = e.message
  ensure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Unsealer</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <link href="https://www.herokucdn.com/purple/1.1.2/purple.min.css" rel="stylesheet" />
  <%= csrf_meta_tags %>
</head>
<body>
  <header id="header" style="margin-bottom: 50px; padding:80px" class="gradient-primary">
    <div class="container text-center" id="flex-item">
      <h1 class="purple-logo">Unseal the vault</h1>
    </div>
  </header>

  <div class="container text-center">
    <% if flash[:error] %>
      <div class="alert alert-danger">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <% if flash[:notice] %>
      <div class="alert alert-info">
        <p><%= flash[:notice] %></p>
      </div>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/unsealer/index.html.erb
<% if current_user %>
  <div class="user u-margin-Al u-padding-Al">
    <img class="small" style="height: 50px; width: 50px" src="<%=current_user.image%>"/>
    <%= current_user.name %> (<%= current_user.email %>)
    <%= link_to 'Disconnect', sessions_path, method: :delete %>
  </div>
  <form action="/unsealer" method="post">
    <button class="btn btn-danger btn-lg">Start unsealing vault</button>
  </form>
<% else %>
  <% case ENV["AUTH"] %>
  <% when "heroku" %>
    <a href="/auth/heroku" class="btn btn-lg btn-default">Unseal with Heroku</a>
  <% when "github" %>
    <a href="/auth/github" class="btn btn-lg btn-default">Unseal with GitHub</a>
  <% when "google" %>
    <a href="/auth/google_oauth2" class="btn btn-lg btn-default">Unseal with Google</a>
  <% end %>
<% end%>

app/views/unsealers/index.html.erb
<h2 title="Sealed:<%= @status.sealed %> | t: <%= @status.t %> | n: <%= @status.n %> | progress: <%= @status.progress %>">Vault status: <% if @status.sealed %>🔒<% else %>🔓<% end %></h2>
<%if @status.sealed %>
  <h4>Shards unlocked</h4>
  <div class="col-md-4 col-md-offset-4">
    <div class="progress">
      <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="<%= @status.progress %>" aria-valuemin="0" aria-valuemax="<%= @status.t %>" style="width: <%= ((@status.progress.to_f / @status.t.to_f) * 100).to_i %>%;">
        <%= @status.progress %> out of <%= @status.t %>
      </div>
    </div>
  </div>
<% end %>

<% if current_user %>
  <div class="user u-margin-Al u-padding-Al">
    <img class="small" style="border-radius: 40px; height: 50px; width: 50px" src="<%=current_user.image%>"/>
    <%= current_user.name %> (<%= current_user.email %>)
    <%= link_to 'Disconnect', sessions_path, method: :delete %>
  </div>
  <% if @status.sealed %>
    <%= form_tag(unsealers_path, method: :post) do %>
      <button class="btn btn-primary btn-lg">Unseal with this shard</button>
    <% end %>
  <% else %>
    <%= form_tag(unsealers_path, method: :delete) do %>
      <button class="btn btn-danger btn-lg">SEAL THE VAULT!!!</button>
    <% end %>
  <% end %>
<% else %>
  <div>
    <% case ENV["AUTH"] %>
    <% when "heroku" %>
      <a href="/auth/heroku" class="btn btn-lg btn-default">Unseal with Heroku</a>
    <% when "github" %>
      <a href="/auth/github" class="btn btn-lg btn-default">Unseal with GitHub</a>
    <% when "google" %>
      <a href="/auth/google_oauth2" class="btn btn-lg btn-default">Unseal with Google</a>
    <% end %>
  </div>
<% end%>